name: tests

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3', '8.4']
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPUnit
        run: vendor/bin/phpunit --colors=always

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --level=9

      - name: Run PHPCS
        run: vendor/bin/phpcs src --standard=PSR12
